### ISSUE TITLE
It also work on binaries? or just scripts?

### ISSUE THREAD

**Issue by dr4lekhine** [bobby-tablez/IP-Obfuscator#1]
Hello,

Kudos for the tool.

I wanted to ask if you know if this same method also works for hardcoded IP adresses on binaries, and in which type of them. For example, for converting the Command & Control server IP addresses to this format.

Thank you.

Regards.

**Comment by bobby-tablez** [comment]
I think the answer is, maybe? I built a quick C# application to test this theory and it appears to work as indented. Can confirm in Sysmon logs that the ping did initiate from the application to the encoded version of 1.1.1.1, in this case

```
using System;
using System.Net;
using System.Net.NetworkInformation;

class Program
{
    static void Main()
    {
        string EncodedIP = "0x1.65793"; // 1.1.1.1

        Console.WriteLine("Pinging IP address: " + EncodedIP);

        Ping pingSender = new Ping();
        PingReply reply = pingSender.Send(EncodedIP);

        if (reply.Status == IPStatus.Success)
        {
            Console.WriteLine("Ping successful. Round-trip time: " + reply.RoundtripTime + " ms");
        }
        else
        {
            Console.WriteLine("Ping failed. Status: " + reply.Status.ToString());
        }
    }
}
```

Hope this helps!

**Comment by dr4lekhine** [comment]
> I think the answer is, maybe? I built a quick C# application to test this theory and it appears to work as indented. Can confirm in Sysmon logs that the ping did initiate from the application to the encoded version of 1.1.1.1, in this case
> 
> ```
> using System;
> using System.Net;
> using System.Net.NetworkInformation;
> 
> class Program
> {
>     static void Main()
>     {
>         string EncodedIP = "0x1.65793"; // 1.1.1.1
> 
>         Console.WriteLine("Pinging IP address: " + EncodedIP);
> 
>         Ping pingSender = new Ping();
>         PingReply reply = pingSender.Send(EncodedIP);
> 
>         if (reply.Status == IPStatus.Success)
>         {
>             Console.WriteLine("Ping successful. Round-trip time: " + reply.RoundtripTime + " ms");
>         }
>         else
>         {
>             Console.WriteLine("Ping failed. Status: " + reply.Status.ToString());
>         }
>     }
> }
> ```
> 
> Hope this helps!

Thank you! I´m closing the issue
